version: '3.9'

services: 
  mongo:
    container_name: web3-voting-mongo 
    hostname: web3-voting-mongo 
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data:
    driver: local
    